apiVersion: v1
kind: Pod
metadata:
  name: pod-4
  labels:
    env: hardware
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: hardware
            operator: In
            values:
            - pod-3  
        topologyKey: topology.kubernetes.io/zone    
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: "hardware"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"
