apiVersion: v1
kind: Pod
metadata:
  name: pod-5
  labels:
    env: hardware1
spec:
  affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: env
                operator: In
                values:
                - hardware
            topologyKey: "kubernetes.io/hostname"
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: "hardware"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"
